## Question 1
### Implement 8x3x8 Neural network and show it can solve autoencoder problem.

In [1]:
from hw4 import neuralnetwork as NN
import numpy as np
import timeit

#### These are my inputs for the autoencoder:
#### Each row is a separate training example.

In [2]:
inputs = ['10000000','01000000','00100000','00010000','00001000','00000100','00000010','00000001']
for item in inputs:
    print(NN.transform_string(item))

[ 1.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  1.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  1.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  1.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  1.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  1.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  1.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  1.]


In [3]:
######start time
start = timeit.default_timer()
#####
model = NN.NeuralNet(8,3,8,2.0,0.01)
iterations = 800
for i in range(iterations):
    model.clear_deltas()
    for item in inputs:
        model.prop_forward(NN.transform_string(item),NN.transform_string(item))
        model.prop_backward()
#######stop time
stop = timeit.default_timer()

#### Here is the runtime for 800 iterations which solves the autoencoder problem.
#### It runs in under one second to train this NN so code seems reasonably implemented.

In [4]:
print('Time: ', stop - start)  

Time:  0.6838353159982944


#### Here are the outputs of the autoencoder model. 
#### Clearly it is the same as the inputs, which is what we expect since we built this as an autoencoder (ie outputs = inputs).

In [5]:
for item in inputs:
    model.prop_forward(NN.transform_string(item),NN.transform_string(item))
    print(np.round(model.layer3_activation))

[ 1.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  1.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  1.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  1.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  1.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  1.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  1.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  1.]
